# Name of the job
name: Continuous Integration

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      # Get the Source Code from GitHub
      - name: Checkout Source Code
        uses: actions/checkout@v2

      # Set up JDK16
      - name: Set up JDK16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'

      # Verify that pom.xml is semantically valid
      - name: Verify package is valid
        run: mvn --batch-mode package
        env:
          # https://github.com/Kotlin/dokka/issues/2023
          MAVEN_OPTS: "--illegal-access=permit"
